steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/shopify-app-csv-fomatter:$COMMIT_SHA', '.']

  # DockerイメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/shopify-app-csv-fomatter:$COMMIT_SHA']

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'run', 'deploy', 'csv-formatter-app',
      '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/shopify-app-csv-fomatter:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', 'asia-northeast1',
      '--allow-unauthenticated',
      '--set-env-vars', 'ALLOWED_ORIGINS=*'
    ]

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/shopify-app-csv-fomatter:$COMMIT_SHA'

substitutions:
  _PROJECT_ID: 'shopify-app-csv-formatter'
  _SERVICE_NAME: 'csv-formatter-app'
