# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1606189b812acddeb628965c01e43be0"
name = "csv-formatter"
handle = "csv-formatter-2"
application_url = "https://lang-thru-houston-joy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kobe-pottery.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://lang-thru-houston-joy.trycloudflare.com/auth/callback",
  "https://lang-thru-houston-joy.trycloudflare.com/auth/shopify/callback",
  "https://lang-thru-houston-joy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
